# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PyQtControlPanelv3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(235, 240)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.startFrame = QtGui.QFrame(self.centralwidget)
        self.startFrame.setGeometry(QtCore.QRect(0, 10, 231, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startFrame.sizePolicy().hasHeightForWidth())
        self.startFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startFrame.setFont(font)
        self.startFrame.setAutoFillBackground(True)
        self.startFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.startFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.startFrame.setObjectName(_fromUtf8("startFrame"))
        self.startLabel = QtGui.QLabel(self.startFrame)
        self.startLabel.setGeometry(QtCore.QRect(10, 10, 31, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startLabel.sizePolicy().hasHeightForWidth())
        self.startLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startLabel.setFont(font)
        self.startLabel.setAutoFillBackground(True)
        self.startLabel.setObjectName(_fromUtf8("startLabel"))
        self.nowStartSelect = QtGui.QRadioButton(self.startFrame)
        self.nowStartSelect.setGeometry(QtCore.QRect(40, 10, 61, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nowStartSelect.sizePolicy().hasHeightForWidth())
        self.nowStartSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.nowStartSelect.setFont(font)
        self.nowStartSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.nowStartSelect.setAutoFillBackground(True)
        self.nowStartSelect.setCheckable(True)
        self.nowStartSelect.setChecked(True)
        self.nowStartSelect.setObjectName(_fromUtf8("nowStartSelect"))
        self.laterStartSelect = QtGui.QRadioButton(self.startFrame)
        self.laterStartSelect.setGeometry(QtCore.QRect(90, 10, 61, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.laterStartSelect.sizePolicy().hasHeightForWidth())
        self.laterStartSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.laterStartSelect.setFont(font)
        self.laterStartSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.laterStartSelect.setAutoFillBackground(True)
        self.laterStartSelect.setObjectName(_fromUtf8("laterStartSelect"))
        self.startTimeEdit = QtGui.QDateTimeEdit(self.startFrame)
        self.startTimeEdit.setEnabled(False)
        self.startTimeEdit.setGeometry(QtCore.QRect(10, 40, 71, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startTimeEdit.sizePolicy().hasHeightForWidth())
        self.startTimeEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startTimeEdit.setFont(font)
        self.startTimeEdit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.startTimeEdit.setAutoFillBackground(True)
        self.startTimeEdit.setAccelerated(True)
        self.startTimeEdit.setTime(QtCore.QTime(0, 0, 0))
        self.startTimeEdit.setObjectName(_fromUtf8("startTimeEdit"))
        self.buttonStartSelect = QtGui.QRadioButton(self.startFrame)
        self.buttonStartSelect.setGeometry(QtCore.QRect(150, 10, 61, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonStartSelect.sizePolicy().hasHeightForWidth())
        self.buttonStartSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.buttonStartSelect.setFont(font)
        self.buttonStartSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonStartSelect.setAutoFillBackground(True)
        self.buttonStartSelect.setObjectName(_fromUtf8("buttonStartSelect"))
        self.stopFrame = QtGui.QFrame(self.centralwidget)
        self.stopFrame.setGeometry(QtCore.QRect(0, 100, 231, 80))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopFrame.sizePolicy().hasHeightForWidth())
        self.stopFrame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.stopFrame.setFont(font)
        self.stopFrame.setAutoFillBackground(True)
        self.stopFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.stopFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.stopFrame.setObjectName(_fromUtf8("stopFrame"))
        self.startLabel_2 = QtGui.QLabel(self.stopFrame)
        self.startLabel_2.setGeometry(QtCore.QRect(10, 10, 31, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startLabel_2.sizePolicy().hasHeightForWidth())
        self.startLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.startLabel_2.setFont(font)
        self.startLabel_2.setAutoFillBackground(True)
        self.startLabel_2.setObjectName(_fromUtf8("startLabel_2"))
        self.buttonEndSelect = QtGui.QRadioButton(self.stopFrame)
        self.buttonEndSelect.setGeometry(QtCore.QRect(40, 10, 61, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEndSelect.sizePolicy().hasHeightForWidth())
        self.buttonEndSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.buttonEndSelect.setFont(font)
        self.buttonEndSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.buttonEndSelect.setAutoFillBackground(True)
        self.buttonEndSelect.setChecked(True)
        self.buttonEndSelect.setObjectName(_fromUtf8("buttonEndSelect"))
        self.timeEndSelect = QtGui.QRadioButton(self.stopFrame)
        self.timeEndSelect.setGeometry(QtCore.QRect(110, 10, 61, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timeEndSelect.sizePolicy().hasHeightForWidth())
        self.timeEndSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.timeEndSelect.setFont(font)
        self.timeEndSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.timeEndSelect.setAutoFillBackground(True)
        self.timeEndSelect.setObjectName(_fromUtf8("timeEndSelect"))
        self.sampleEndSelect = QtGui.QRadioButton(self.stopFrame)
        self.sampleEndSelect.setGeometry(QtCore.QRect(160, 10, 71, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleEndSelect.sizePolicy().hasHeightForWidth())
        self.sampleEndSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sampleEndSelect.setFont(font)
        self.sampleEndSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.sampleEndSelect.setAutoFillBackground(True)
        self.sampleEndSelect.setObjectName(_fromUtf8("sampleEndSelect"))
        self.endTimeEdit = QtGui.QDateTimeEdit(self.stopFrame)
        self.endTimeEdit.setEnabled(False)
        self.endTimeEdit.setGeometry(QtCore.QRect(10, 40, 71, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endTimeEdit.sizePolicy().hasHeightForWidth())
        self.endTimeEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.endTimeEdit.setFont(font)
        self.endTimeEdit.setFocusPolicy(QtCore.Qt.TabFocus)
        self.endTimeEdit.setAutoFillBackground(True)
        self.endTimeEdit.setObjectName(_fromUtf8("endTimeEdit"))
        self.sampleSelect = QtGui.QSpinBox(self.stopFrame)
        self.sampleSelect.setEnabled(False)
        self.sampleSelect.setGeometry(QtCore.QRect(100, 40, 57, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sampleSelect.sizePolicy().hasHeightForWidth())
        self.sampleSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.sampleSelect.setFont(font)
        self.sampleSelect.setAutoFillBackground(True)
        self.sampleSelect.setMinimum(10)
        self.sampleSelect.setMaximum(1000)
        self.sampleSelect.setSingleStep(10)
        self.sampleSelect.setProperty("value", 10)
        self.sampleSelect.setObjectName(_fromUtf8("sampleSelect"))
        self.readLabel = QtGui.QLabel(self.centralwidget)
        self.readLabel.setGeometry(QtCore.QRect(10, 190, 71, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readLabel.sizePolicy().hasHeightForWidth())
        self.readLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.readLabel.setFont(font)
        self.readLabel.setAutoFillBackground(True)
        self.readLabel.setObjectName(_fromUtf8("readLabel"))
        self.rateSelect = QtGui.QSpinBox(self.centralwidget)
        self.rateSelect.setGeometry(QtCore.QRect(80, 180, 51, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rateSelect.sizePolicy().hasHeightForWidth())
        self.rateSelect.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.rateSelect.setFont(font)
        self.rateSelect.setFocusPolicy(QtCore.Qt.TabFocus)
        self.rateSelect.setAutoFillBackground(True)
        self.rateSelect.setWrapping(True)
        self.rateSelect.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.rateSelect.setMinimum(1)
        self.rateSelect.setMaximum(10)
        self.rateSelect.setObjectName(_fromUtf8("rateSelect"))
        self.goButton = QtGui.QPushButton(self.centralwidget)
        self.goButton.setGeometry(QtCore.QRect(140, 180, 90, 28))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.goButton.sizePolicy().hasHeightForWidth())
        self.goButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.goButton.setFont(font)
        self.goButton.setFocusPolicy(QtCore.Qt.TabFocus)
        self.goButton.setAutoFillBackground(True)
        self.goButton.setAutoDefault(True)
        self.goButton.setObjectName(_fromUtf8("goButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Photometer", None))
        self.startLabel.setText(_translate("MainWindow", "Start:", None))
        self.nowStartSelect.setStatusTip(_translate("MainWindow", "Start Immediately", None))
        self.nowStartSelect.setText(_translate("MainWindow", "Now", None))
        self.laterStartSelect.setStatusTip(_translate("MainWindow", "Start at a later time", None))
        self.laterStartSelect.setText(_translate("MainWindow", "Later", None))
        self.startTimeEdit.setStatusTip(_translate("MainWindow", "Time to start from", None))
        self.startTimeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm", None))
        self.buttonStartSelect.setStatusTip(_translate("MainWindow", "Start when okay is pressed", None))
        self.buttonStartSelect.setText(_translate("MainWindow", "Button", None))
        self.startLabel_2.setText(_translate("MainWindow", "End:", None))
        self.buttonEndSelect.setStatusTip(_translate("MainWindow", "End When Ok is pressed", None))
        self.buttonEndSelect.setText(_translate("MainWindow", "Button", None))
        self.timeEndSelect.setStatusTip(_translate("MainWindow", "End at a particular Time", None))
        self.timeEndSelect.setText(_translate("MainWindow", "Time", None))
        self.sampleEndSelect.setStatusTip(_translate("MainWindow", "End after n samples have been taken", None))
        self.sampleEndSelect.setText(_translate("MainWindow", "Sample", None))
        self.endTimeEdit.setStatusTip(_translate("MainWindow", "Time to end at", None))
        self.endTimeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm ", None))
        self.sampleSelect.setStatusTip(_translate("MainWindow", "Number of samples to be taken", None))
        self.readLabel.setText(_translate("MainWindow", "Sample Rate:", None))
        self.rateSelect.setStatusTip(_translate("MainWindow", "Number of samples per second", None))
        self.goButton.setText(_translate("MainWindow", "Go", None))

